### ISSUE TITLE
get stacks tracking working

### ISSUE THREAD

**Issue by leibatt** [leibatt/sushi-go#2]
- [x] create functionality for managing hands of cards
- [x] given a hand of cards, pick a card to add to a stack (or create a new stack)
- [ ] given a hand of cards, pick the card resulting in the highest overall score (i.e., write simple greedy AI)
